HTCC7211:
  Co-culture Effect:
    sample_use:
      S01: none
      S02: none
      S03: none
      S04: none
      S05: none
      S06: none
      S07: none
      S08: none
      S09: treatment
      S10: treatment
      S11: treatment
      S12: treatment
      S13: treatment
      S14: treatment
      S15: none
      S16: none
      S17: none
      S18: none
      S19: none
      S20: none
      S21: none
      S22: none
      S23: none
      S24: none
      S25: control
      S26: control
      S27: control
      S28: control
      S29: none
      S30: none
      S31: none
      S32: none
    status: ready
MIT9301:
  Co-culture Effect:
    sample_use:
      S01: control
      S02: control
      S03: control
      S04: control
      S05: none
      S06: none
      S07: none
      S08: none
      S09: treatment
      S10: treatment
      S11: treatment
      S12: treatment
      S13: treatment
      S14: treatment
      S15: none
      S16: none
      S17: none
      S18: none
      S19: none
      S20: none
      S21: none
      S22: none
      S23: none
      S24: none
      S25: none
      S26: none
      S27: none
      S28: none
      S29: none
      S30: none
      S31: none
      S32: none
    status: ready
  Media Effect:
    sample_use:
      S01: treatment
      S02: treatment
      S03: treatment
      S04: treatment
      S05: none
      S06: none
      S07: none
      S08: none
      S09: none
      S10: none
      S11: none
      S12: none
      S13: none
      S14: none
      S15: none
      S16: none
      S17: none
      S18: none
      S19: none
      S20: none
      S21: control
      S22: control
      S23: control
      S24: control
      S25: none
      S26: none
      S27: none
      S28: none
      S29: none
      S30: none
      S31: none
      S32: none
    status: ready
