
samples: "config/samples.tsv"
config: "config/config.yaml"

# options are 'bwa' 'hisat2' and 'bowtie2'
aligner: 'bwa'

experiment_name: '2022_proMortalityExperiment'

htseq:
  mapping_qual_threshold: 10 # default is 10

feature_types_to_keep: [
'CDS',
'rRNA',
'tRNA',
'internal_ref'
]

input: 
  raw_reads: /nfs/chisholmlab001/kve/2022_proMortalityExperiment/input_data/samples
  genome_refs: /nfs/chisholmlab001/kve/2022_proMortalityExperiment/input_data/genomes
  gff_refs: /nfs/chisholmlab001/kve/2022_proMortalityExperiment/input_data/annotations
  adapter_file: /nfs/chisholmlab001/kve/genomic_resources/adapters/illumina/all_illumina_adapters.fa
scratch_dir: /nfs/chisholmlab001/kve/2022_proMortalityExperiment/output_data/
results: /nfs/chisholmlab001/kve/2022_proMortalityExperiment/results_hisat2