
samples: "config/samples.tsv"
config: "config/config.yaml"

# options are 'bwa' 'hisat2' and 'bowtie2'
aligner: 'bwa'

experiment_name: '2021_Sar11Pro_RNAseq_Project'

htseq:
  mapping_qual_threshold: 10 # default is 10

feature_types_to_keep: [
'CDS',
'rRNA',
'tRNA',
'sRNA'
# 'RNase_P_RNA',
# 'pseudogene',
# 'region',
# 'riboswitch',
# 'tmRNA',
]

input: 
  raw_reads: /nfs/chisholmlab001/kve/2021_Sar11Pro_RNAseq_Project/data/input_data/raw_reads
  genome_refs: /nfs/chisholmlab001/kve/2021_Sar11Pro_RNAseq_Project/data/input_data/culture_genome_refs
  gff_refs: /nfs/chisholmlab001/kve/2021_Sar11Pro_RNAseq_Project/data/input_data/culture_genome_annotations
  adapter_file: /nfs/chisholmlab001/kve/2021_Sar11Pro_RNAseq_Project/data/input_data/adapters/all_illumina_adapters.fa
scratch_dir: /nfs/chisholmlab001/kve/2021_Sar11Pro_RNAseq_Project/data/output_data/
results: /nfs/chisholmlab001/kve/2021_Sar11Pro_RNAseq_Project/data/results_bwa_corrected