
samples: "config/samples.tsv"

use_bwa: true
use_hisat2: false

htseq:
  mapping_qual_threshold: 10 # default is 10

input: 
  raw_reads: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/input_data/raw_reads
  genome_refs: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/input_data/culture_genome_refs
  gff_refs: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/input_data/culture_genome_annotations
  adapter_file: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/input_data/adapters/all_illumina_adapters.fa
output: 
  done_files: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/done_files
  trimmed_reads: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/trimmed_reads
  concat_gff:
    concat_gff_file: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/concat_gff/concat_gff.gff
    concat_gff_mod_file: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/concat_gff/concat_gff_mod.gff
  concat_genome: 
    concat_genome_file: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/concat_genome/concat_genome.fna
    concat_genome_done: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/concat_genome/indexed.done
  mapped_reads: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/mapped_reads
  feature_count: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/HTseq
  genome_index_parent: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/genome_index
  library_count: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/raw_library_counts/library_len.tsv
  coverage_positions: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/coverage_positions
  fastqc: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/output_data/fastqc
results: /nfs/chisholmlab001/kve/2021_dark_adapted_transcriptome/results

  

